/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.so.cdct;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ItemMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3843684931952984374L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ItemMessage\",\"namespace\":\"com.so.cdct\",\"fields\":[{\"name\":\"code\",\"type\":\"string\"},{\"name\":\"reservePrice\",\"type\":[\"int\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ItemMessage> ENCODER =
      new BinaryMessageEncoder<ItemMessage>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ItemMessage> DECODER =
      new BinaryMessageDecoder<ItemMessage>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ItemMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ItemMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ItemMessage>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ItemMessage to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ItemMessage from a ByteBuffer. */
  public static ItemMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence code;
  @Deprecated public java.lang.Integer reservePrice;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ItemMessage() {}

  /**
   * All-args constructor.
   * @param code The new value for code
   * @param reservePrice The new value for reservePrice
   */
  public ItemMessage(java.lang.CharSequence code, java.lang.Integer reservePrice) {
    this.code = code;
    this.reservePrice = reservePrice;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return code;
    case 1: return reservePrice;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: code = (java.lang.CharSequence)value$; break;
    case 1: reservePrice = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'code' field.
   * @return The value of the 'code' field.
   */
  public java.lang.CharSequence getCode() {
    return code;
  }

  /**
   * Sets the value of the 'code' field.
   * @param value the value to set.
   */
  public void setCode(java.lang.CharSequence value) {
    this.code = value;
  }

  /**
   * Gets the value of the 'reservePrice' field.
   * @return The value of the 'reservePrice' field.
   */
  public java.lang.Integer getReservePrice() {
    return reservePrice;
  }

  /**
   * Sets the value of the 'reservePrice' field.
   * @param value the value to set.
   */
  public void setReservePrice(java.lang.Integer value) {
    this.reservePrice = value;
  }

  /**
   * Creates a new ItemMessage RecordBuilder.
   * @return A new ItemMessage RecordBuilder
   */
  public static com.so.cdct.ItemMessage.Builder newBuilder() {
    return new com.so.cdct.ItemMessage.Builder();
  }

  /**
   * Creates a new ItemMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ItemMessage RecordBuilder
   */
  public static com.so.cdct.ItemMessage.Builder newBuilder(com.so.cdct.ItemMessage.Builder other) {
    return new com.so.cdct.ItemMessage.Builder(other);
  }

  /**
   * Creates a new ItemMessage RecordBuilder by copying an existing ItemMessage instance.
   * @param other The existing instance to copy.
   * @return A new ItemMessage RecordBuilder
   */
  public static com.so.cdct.ItemMessage.Builder newBuilder(com.so.cdct.ItemMessage other) {
    return new com.so.cdct.ItemMessage.Builder(other);
  }

  /**
   * RecordBuilder for ItemMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ItemMessage>
    implements org.apache.avro.data.RecordBuilder<ItemMessage> {

    private java.lang.CharSequence code;
    private java.lang.Integer reservePrice;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.so.cdct.ItemMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.code)) {
        this.code = data().deepCopy(fields()[0].schema(), other.code);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.reservePrice)) {
        this.reservePrice = data().deepCopy(fields()[1].schema(), other.reservePrice);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ItemMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(com.so.cdct.ItemMessage other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.code)) {
        this.code = data().deepCopy(fields()[0].schema(), other.code);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.reservePrice)) {
        this.reservePrice = data().deepCopy(fields()[1].schema(), other.reservePrice);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'code' field.
      * @return The value.
      */
    public java.lang.CharSequence getCode() {
      return code;
    }

    /**
      * Sets the value of the 'code' field.
      * @param value The value of 'code'.
      * @return This builder.
      */
    public com.so.cdct.ItemMessage.Builder setCode(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.code = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'code' field has been set.
      * @return True if the 'code' field has been set, false otherwise.
      */
    public boolean hasCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'code' field.
      * @return This builder.
      */
    public com.so.cdct.ItemMessage.Builder clearCode() {
      code = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'reservePrice' field.
      * @return The value.
      */
    public java.lang.Integer getReservePrice() {
      return reservePrice;
    }

    /**
      * Sets the value of the 'reservePrice' field.
      * @param value The value of 'reservePrice'.
      * @return This builder.
      */
    public com.so.cdct.ItemMessage.Builder setReservePrice(java.lang.Integer value) {
      validate(fields()[1], value);
      this.reservePrice = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'reservePrice' field has been set.
      * @return True if the 'reservePrice' field has been set, false otherwise.
      */
    public boolean hasReservePrice() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'reservePrice' field.
      * @return This builder.
      */
    public com.so.cdct.ItemMessage.Builder clearReservePrice() {
      reservePrice = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ItemMessage build() {
      try {
        ItemMessage record = new ItemMessage();
        record.code = fieldSetFlags()[0] ? this.code : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.reservePrice = fieldSetFlags()[1] ? this.reservePrice : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ItemMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<ItemMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ItemMessage>
    READER$ = (org.apache.avro.io.DatumReader<ItemMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
